import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, Bot, BriefcaseBusiness, CheckCircle2, ChevronDown, ChevronRight, CircleDot, FolderKanban, LayoutGrid, MessageSquare, Radio, Send, Sparkles, UserRound, X } from 'lucide-react'
import { followExecution, readExecutionFallback } from '../commandCenterApi'
import { answerWorkClarification, createDirectWorkItem, submitWorkFeedback } from '../lifeOSApi'
import { ACTIVE, LABEL, commandMode, contextText, isStalled, legacySnapshot } from '../lib/commandCenterModel'
import './command-center.css'

const FALLBACK=[{id:'hy',name:'HY',mission:'Life OS 治理、方向與跨域協調'},{id:'950157',name:'950157',mission:'研發、本業與技術執行'},{id:'sam',name:'Sam',mission:'事業發展與營運'},{id:'family',name:'小因',mission:'家庭、生活與平衡'}]
const CONN={live:'即時',connecting:'連線中',disconnected:'已斷線',stale:'同步異常',paused:'已暫停',snapshot:'狀態快照'}
const time=v=>v?new Date(v).toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Taipei'}):'未回報'
const tone=s=>['waiting','review'].includes(s)?'attention':['failed','cancelled'].includes(s)?'danger':ACTIVE.has(s)?'active':s==='succeeded'?'done':'neutral'
const mark=o=>o.id==='family'?'因':o.id==='950157'?'研':(o.name||o.id).slice(0,2)
function Badge({item,now}){return <span className={`p5-badge is-${tone(item.status)}`}><i/>{LABEL[item.status]||item.status||'未回報'}{isStalled(item,now)?' · 久未更新':''}</span>}
function Empty({title,text}){return <div className="p5-empty"><CircleDot size={19}/><b>{title}</b>{text&&<span>{text}</span>}</div>}

export default function CommandCenter(){
 const [data,setData]=useState(null),[connection,setConnection]=useState('connecting'),[error,setError]=useState('')
 const [view,setView]=useState({level:'home',bot:'hy'}),[briefOpen,setBriefOpen]=useState(false),[activityOpen,setActivityOpen]=useState(false),[drawerOpen,setDrawerOpen]=useState(false),[overviewOpen,setOverviewOpen]=useState(false)
 const [command,setCommand]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(null),[now,setNow]=useState(Date.now()),[height,setHeight]=useState(null)
 const dataRef=useRef(null),viewRef=useRef(null)
 const offices=data?.offices||FALLBACK,work=data?.work||[],events=data?.events||[]
 const selected=work.find(w=>w.work===view.work)
 const attention=work.filter(w=>isStalled(w,now)||['waiting','review','failed'].includes(w.status))
 const working=work.filter(w=>ACTIVE.has(w.status)&&!isStalled(w,now))
 const results=work.filter(w=>['review','succeeded'].includes(w.status)).sort((a,b)=>Date.parse(b.updated_at)-Date.parse(a.updated_at))
 const projects=useMemo(()=>{const m=new Map();for(const w of work){const id=w.project||'__unassigned__';if(!m.has(id))m.set(id,{id,name:w.project_name||'未指定 Project',work:[],updated_at:w.updated_at});const p=m.get(id);p.work.push(w);if(Date.parse(w.updated_at)>Date.parse(p.updated_at))p.updated_at=w.updated_at}return [...m.values()].sort((a,b)=>Date.parse(b.updated_at)-Date.parse(a.updated_at))},[work])
 const project=projects.find(p=>p.id===view.project),office=offices.find(o=>o.id===view.bot)||offices[0]
 const selection={bot:view.bot||project?.work[0]?.bot||'hy',agent:selected?.agent,agent_name:selected?.agent_name,project:project?.id||selected?.project,project_name:project?.name||selected?.project_name,work:selected?.work}
 const mode=commandMode(selection,work),context=contextText(selection,offices,work)
 dataRef.current=data;viewRef.current=view
 useEffect(()=>{let stop=false,controller,timer,attempt=0;async function connect(){if(stop||document.hidden)return;controller=new AbortController();setConnection('connecting');try{await followExecution({signal:controller.signal,onSnapshot:v=>{setData(v);setError('');attempt=0},onState:setConnection})}catch(e){if(stop||controller.signal.aborted)return;setConnection('disconnected');setError(e.message);try{const core=await readExecutionFallback(controller.signal);if(stop||controller.signal.aborted)return;setData(legacySnapshot(core,FALLBACK));setConnection('snapshot');setError('即時串流尚未連線；目前顯示既有後端的狀態快照。')}catch{}}if(!stop&&!document.hidden)timer=setTimeout(connect,Math.min(30000,1000*2**attempt++))}const visibility=()=>{clearTimeout(timer);controller?.abort();document.hidden?setConnection('paused'):connect()};connect();document.addEventListener('visibilitychange',visibility);return()=>{stop=true;clearTimeout(timer);controller?.abort();document.removeEventListener('visibilitychange',visibility)}},[])
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(id)},[])
 useEffect(()=>{const v=window.visualViewport;if(!v)return;const resize=()=>setHeight(v.height);resize();v.addEventListener('resize',resize);return()=>v.removeEventListener('resize',resize)},[])
 useEffect(()=>{const api=Object.freeze({version:2,getContext:()=>({...viewRef.current}),getSnapshot:()=>structuredClone(dataRef.current),capabilities:['read_context','read_execution']});window.hyCommandCenter=api;return()=>{if(window.hyCommandCenter===api)delete window.hyCommandCenter}},[])
 useEffect(()=>setNotice(null),[view])
 const home=()=>{setView({level:'home',bot:view.bot||'hy'});setDrawerOpen(false)}
 const openProject=p=>{setView({level:'project',project:p.id,bot:p.work[0]?.bot||'hy'});setDrawerOpen(false)}
 const openBot=bot=>{setView({level:'bot',bot});setDrawerOpen(false)}
 const openWork=w=>{const p=projects.find(x=>x.id===(w.project||'__unassigned__'));setView({level:'project',project:p?.id,bot:w.bot,work:w.work});setDrawerOpen(true)}
 async function submit(){const text=command.trim();if(!text||busy||mode.kind==='blocked')return;setBusy(true);setNotice(null);try{let r;if(mode.kind==='clarification')r=await answerWorkClarification(selected.work,text);else if(mode.kind==='feedback')r=await submitWorkFeedback(selected.work,text,`hy-command-feedback-${selected.work}-${Date.now()}`);else r=await createDirectWorkItem({title:text.split(/\r?\n/)[0].slice(0,80),desc:text,milestoneId:`command-${Date.now()}`,owner:selection.bot||'hy',projectId:selection.project||undefined,projectName:selection.project_name||undefined});setCommand('');setNotice({type:'success',text:mode.kind==='clarification'?'已回覆同一筆工作，Bot 將繼續執行。':mode.kind==='feedback'?'已在同專案建立下一輪修訂工作。':`已建立 1 筆 AI Work${r.item?.id?`：${r.item.id}`:''}`})}catch(e){setNotice({type:'error',text:e.message||'指令送出失敗'})}finally{setBusy(false)}}

 const Brief=<aside className={`p5-side p5-brief ${briefOpen?'is-open':''}`}><div className="p5-side-head"><div><small>NOW</small><h2>Brief</h2></div><button onClick={()=>setBriefOpen(false)}><X size={18}/></button></div><div className="p5-kpis"><div><b>{data?attention.length:'—'}</b><span>Needs You</span></div><div><b>{data?working.length:'—'}</b><span>Working</span></div><div><b>{data?results.length:'—'}</b><span>Results</span></div></div><h3>需要你處理</h3>{attention.slice(0,5).map(w=><button className="p5-mini-work" key={w.work} onClick={()=>{openWork(w);setBriefOpen(false)}}><Badge item={w} now={now}/><b>{w.title}</b><small>{time(w.updated_at)}</small></button>)}{data&&!attention.length&&<Empty title="目前沒有待處理項目"/>}<h3>System Improvement</h3>{(data?.system_improvements||[]).map(x=><div className="p5-note" key={x.id}><b>{x.title}</b><span>{x.detail}</span><small>建議 · 待 HY 核准</small></div>)}{data&&!data.system_improvements?.length&&<p className="p5-muted">目前沒有規則巡查建議。</p>}</aside>
 const ActivityPanel=<aside className={`p5-side p5-activity ${activityOpen?'is-open':''}`}><div className="p5-side-head"><div><small>REAL EVENTS</small><h2>Activity</h2></div><button onClick={()=>setActivityOpen(false)}><X size={18}/></button></div><p className="p5-muted">只顯示後端實際回報 · 台北時間</p>{[...events].reverse().slice(0,30).map(e=><button className="p5-event" key={e.id} onClick={()=>{const w=work.find(x=>x.work===e.data.work);if(w)openWork(w);setActivityOpen(false)}}><i/><time>{time(e.occurredAt)}</time><b>{offices.find(o=>o.id===e.data.bot)?.name||e.data.bot} · {e.data.agent_name||'未標示 Agent'}</b><span>{e.data.current_activity||LABEL[e.data.status]||e.data.status}</span>{e.data.handoff&&<small>交接 {e.data.handoff.from_bot} → {e.data.handoff.to_bot}</small>}</button>)}{data&&!events.length&&<Empty title={connection==='snapshot'?'即時事件尚未連線':'尚無執行事件'} text="不會以模擬動畫代替真實回報。"/>}</aside>

 const Home=()=> <main className="p5-main p5-home"><section className="p5-hero"><div><small>PERSONAL AI OPERATING SYSTEM</small><h2>今天需要你看什麼？</h2><p>決策、執行與成果都從真實 AI Work 狀態彙整。</p></div><Link to="/dispatch">全部 AI 工作 <ArrowUpRight size={16}/></Link></section>{error&&<div className="p5-warning">{error}</div>}
  <Section icon={<Sparkles/>} tone="attention" title="Needs You" sub="等待補充、待驗收與異常" count={attention.length}>{attention.length?<div className="p5-card-grid">{attention.slice(0,6).map(w=><button className="p5-work-card" key={w.work} onClick={()=>openWork(w)}><div><Badge item={w} now={now}/><span>{time(w.updated_at)}</span></div><h4>{w.title}</h4><p>{w.current_activity||w.waiting_for||'等待你檢視工作狀態'}</p><footer><span>{offices.find(o=>o.id===w.bot)?.name||w.bot}</span><ArrowRight size={15}/></footer></button>)}</div>:data&&<Empty title="清空了" text="目前沒有等待你介入的 AI Work。"/>}</Section>
  <Section icon={<Activity/>} tone="active" title="Working Now" sub="Bot 正在實際執行的工作" count={working.length}>{working.length?<div className="p5-list">{working.slice(0,6).map(w=><button key={w.work} onClick={()=>openWork(w)}><Avatar office={offices.find(o=>o.id===w.bot)||{id:w.bot,name:w.bot}}/><span><b>{w.title}</b><small>{w.agent_name||'未標示 Agent'} · {w.current_activity||LABEL[w.status]}</small></span><Badge item={w} now={now}/><ChevronRight/></button>)}</div>:data&&<Empty title="目前沒有執行中的工作" text="派工後，真實進度會出現在這裡。"/>}</Section>
  <div className="p5-two"><Section icon={<CheckCircle2/>} tone="done" title="Recent Results" sub="最近交付與待驗收成果"><div className="p5-list compact">{results.slice(0,5).map(w=><button key={w.work} onClick={()=>openWork(w)}><span><b>{w.title}</b><small>{w.project_name||'未指定 Project'} · {time(w.updated_at)}</small></span><Badge item={w} now={now}/></button>)}</div>{data&&!results.length&&<Empty title="尚無近期成果"/>}</Section><Section icon={<FolderKanban/>} tone="project" title="Projects" sub="依既有 Project ID 彙整" count={projects.length}><div className="p5-list compact">{projects.slice(0,6).map(p=><button key={p.id} onClick={()=>openProject(p)}><span><b>{p.name}</b><small>{p.work.length} work · {time(p.updated_at)}</small></span><ChevronRight/></button>)}</div>{data&&!projects.length&&<Empty title="尚無 Project 工作"/>}</Section></div>
  <Section icon={<Bot/>} tone="bot" title="Bot Roster" sub="角色、狀態與目前焦點"><div className="p5-bots">{offices.map(o=>{const ws=work.filter(w=>w.bot===o.id),active=ws.find(w=>ACTIVE.has(w.status));return <button key={o.id} onClick={()=>openBot(o.id)}><Avatar office={o} large/><span><b>{o.name}</b><small>{o.mission}</small><em>{active?active.current_activity||LABEL[active.status]:'Idle'}</em></span><ChevronRight/></button>})}</div></Section>
  <section className="p5-overview"><button onClick={()=>setOverviewOpen(v=>!v)}><span><LayoutGrid/><b>Office Overview</b><small>次要空間總覽，不代表工作進度</small></span>{overviewOpen?<ChevronDown/>:<ChevronRight/>}</button>{overviewOpen&&<div><p>空間視圖已降為輔助入口。工作狀態以本頁與後端事件為準。</p>{offices.map(o=><button key={o.id} onClick={()=>openBot(o.id)}><Avatar office={o}/><b>{o.name}</b></button>)}</div>}</section></main>

 const Project=()=>{const pw=project?.work||[],ids=new Set(pw.map(w=>w.work)),pe=events.filter(e=>ids.has(e.data.work)).sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt));const timeline=pe.length?pe.map(e=>({...e.data,id:e.id,at:e.occurredAt})):pw.map(w=>({...w,id:w.work,at:w.updated_at}));return <main className="p5-main"><LevelHead onBack={home} label="PROJECT CHANNEL" title={project?.name||'Project'} sub={`${pw.length} AI Work · 最後更新 ${time(project?.updated_at)}`} action={<button className="p5-drawer-toggle" onClick={()=>setDrawerOpen(v=>!v)}><BriefcaseBusiness/> Work Drawer <b>{pw.length}</b></button>}/><div className="p5-channel"><section className="p5-timeline"><div className="p5-intro"><FolderKanban/><div><b>專案活動</b><p>timeline 只整理既有 AI Work 與後端事件；一般討論不會自動建工。</p></div></div>{timeline.map(x=><article key={x.id}><span className={`is-${tone(x.status)}`}><Radio/></span><div><header><b>{offices.find(o=>o.id===x.bot)?.name||x.bot}</b><time>{time(x.at)}</time></header><p>{x.current_activity||x.title||LABEL[x.status]}</p>{x.title&&<small>{x.title}</small>}{x.handoff&&<em>Handoff · {x.handoff.from_bot} → {x.handoff.to_bot}</em>}<Badge item={x} now={now}/></div></article>)}{data&&!timeline.length&&<Empty title="這個 Project 尚無 AI Work"/>}</section><aside className={`p5-drawer ${drawerOpen?'is-open':''}`}><div className="p5-drawer-head"><div><small>EXISTING AI WORK</small><h3>Work Drawer</h3></div><button onClick={()=>setDrawerOpen(false)}><X/></button></div>{pw.map(w=><button className={view.work===w.work?'selected':''} key={w.work} onClick={()=>setView(v=>({...v,bot:w.bot,work:w.work}))}><Badge item={w} now={now}/><b>{w.title}</b><small>{w.agent_name||'未標示 Agent'} · {time(w.updated_at)}</small></button>)}{selected&&<dl><dt>Stage</dt><dd>{selected.stage||'未回報'}</dd><dt>Current</dt><dd>{selected.current_activity||'尚無活動回報'}</dd><dt>Waiting for</dt><dd>{selected.waiting_for||'—'}</dd><dt>Lifecycle / Execution</dt><dd>{selected.lifecycle_status} / {selected.status}</dd><dt>Work ID</dt><dd>{selected.work}</dd><dt>Result / Approval</dt><dd><Link to="/dispatch">開啟既有 AI 工作中心 ↗</Link></dd></dl>}</aside></div></main>}

 const BotView=()=>{const bw=work.filter(w=>w.bot===office.id),run=bw.filter(w=>ACTIVE.has(w.status)),done=bw.filter(w=>['review','succeeded'].includes(w.status)),ps=projects.filter(p=>p.work.some(w=>w.bot===office.id));return <main className="p5-main"><LevelHead onBack={home} label="SINGLE BOT" title={office.name} sub={office.mission} avatar={<Avatar office={office} large/>}/><div className="p5-profile"><Profile icon={<UserRound/>} title="Persona" wide><h3>{office.name} Office</h3><p>{office.mission||'角色說明由既有 Bot 設定維護。'}</p><small>沿用既有 persona 與 owner 邊界，不建立第二套 Bot schema。</small></Profile><Profile icon={<CircleDot/>} title="Focus"><h3>{run[0]?.current_activity||run[0]?.title||'目前沒有執行焦點'}</h3><p>{run[0]?`${LABEL[run[0].status]} · ${time(run[0].updated_at)}`:'Idle'}</p></Profile><Profile icon={<Activity/>} title="Working"><h3>{run.length}</h3><p>真實執行中的 AI Work</p></Profile><Profile icon={<CheckCircle2/>} title="Results" wide><div className="p5-list compact">{done.slice(0,4).map(w=><button key={w.work} onClick={()=>openWork(w)}><span><b>{w.title}</b><small>{time(w.updated_at)}</small></span><Badge item={w} now={now}/></button>)}</div>{!done.length&&<Empty title="尚無近期成果"/>}</Profile><Profile icon={<MessageSquare/>} title="Memory"><h3>既有治理</h3><p>記憶由 HY Life OS 現有 Memory schema 維護，此頁不複製或推測內容。</p><Link to="/helpers">開啟角色與記憶 ↗</Link></Profile><Profile icon={<FolderKanban/>} title="Projects"><h3>{ps.length}</h3><div className="p5-chips">{ps.slice(0,5).map(p=><button key={p.id} onClick={()=>openProject(p)}>{p.name}</button>)}</div></Profile></div></main>}

 return <div className="p5-root" style={height?{'--vh':`${height}px`}:undefined}><header className="p5-header"><Link to="/"><ArrowLeft/></Link><button className="p5-brand" onClick={home}><span>HY LIFE OS</span><b>Command Center <em>V2</em></b></button><nav><button className={view.level==='home'?'active':''} onClick={home}>Home</button><button className={view.level==='project'?'active':''} onClick={()=>projects[0]&&openProject(projects[0])}>Projects</button><button className={view.level==='bot'?'active':''} onClick={()=>openBot(view.bot||'hy')}>Bots</button></nav><span className={`p5-connection is-${connection}`}><i/>{CONN[connection]}</span><Link className="p5-ai-work" to="/dispatch">AI Work <ArrowUpRight/></Link></header><div className="p5-mobile"><button onClick={()=>setBriefOpen(true)}>Brief <b>{attention.length}</b></button><button className={view.level==='home'?'active':''} onClick={home}>Home</button><button onClick={()=>setActivityOpen(true)}>Activity <b>{events.length}</b></button></div><div className="p5-shell">{Brief}{view.level==='project'?<Project/>:view.level==='bot'?<BotView/>:<Home/>}{ActivityPanel}</div>{(briefOpen||activityOpen)&&<button className="p5-scrim" onClick={()=>{setBriefOpen(false);setActivityOpen(false)}}/>}<footer className="p5-command"><div><span>COMMAND BAR</span><b>{context||'HY'}</b>{selected&&<Badge item={selected} now={now}/>}</div><section><MessageSquare/><input value={command} aria-label="工作指令或回覆" disabled={mode.kind==='blocked'||busy} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submit()}}} placeholder={mode.placeholder}/><button disabled={!command.trim()||mode.kind==='blocked'||busy} onClick={submit}><Send/><span>{busy?'送出中':mode.label}</span></button></section><p className={notice?.type||''}>{notice?.text||mode.helper}</p></footer></div>
}

function Avatar({office,large}){return <span className={`p5-avatar ${large?'large':''} a-${office.id}`}>{mark(office)}</span>}
function Section({icon,tone,title,sub,count,children}){return <section className="p5-section"><div className="p5-section-title"><div><span className={`p5-section-icon ${tone}`}>{icon}</span><div><h3>{title}</h3><p>{sub}</p></div></div>{count!==undefined&&<b>{count}</b>}</div>{children}</section>}
function LevelHead({onBack,label,title,sub,action,avatar}){return <div className="p5-level-head"><button onClick={onBack}><ArrowLeft/> Home</button>{avatar}<div><small>{label}</small><h2>{title}</h2><p>{sub}</p></div>{action}</div>}
function Profile({icon,title,wide,children}){return <section className={`p5-profile-card ${wide?'wide':''}`}><span>{icon}{title}</span>{children}</section>}
