import { useState, useEffect } from 'react'
import { authHeaders } from '../auth'
import './expert-team.css'

const base=import.meta.env.VITE_API_BASE || ''
async function api(path,body) {
  const res=await fetch(`${base}/api/ai-work-packages${path}`,{method:body?'POST':'GET',headers:{...authHeaders(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'})
  const data=await res.json()
  if(!res.ok)throw new Error(data.detail||data.error||`HTTP ${res.status}`)
  return data
}
function Avatar(){return <svg className="pi-avatar" viewBox="0 0 100 100" role="img" aria-label="PI 數位幻影"><circle cx="50" cy="50" r="44" fill="var(--hy-ai-bg)"/><g fill="none" stroke="var(--hy-brand)"><ellipse cx="50" cy="50" rx="39" ry="15" opacity=".35"/><ellipse cx="50" cy="50" rx="29" ry="41" strokeDasharray="3 5" opacity=".5"/><path d="M26 83Q29 62 40 58M60 58Q71 62 74 83M32 29 50 17 68 29 66 50 50 62 34 50Z" strokeWidth="2"/><path d="m32 29 18 9 18-9M50 38v24M34 50l16-12 16 12" opacity=".6"/><path d="M25 70h50M21 77h58M29 84h42" opacity=".45"/><path d="M40 42h7m6 0h7" strokeWidth="3"/></g></svg>}
function grouped(rows=[]){return Object.values(rows.reduce((out,row)=>{(out[row.id] ||= []).push(row);return out},{})).map(rows=>rows.sort((a,b)=>b.version.localeCompare(a.version,undefined,{numeric:true})))}
function Status({state}){return <span className="hy-pill" data-s={state==='PUBLISHED'?'done':'you'}>{stateLabel[state]||state}</span>}

const stateLabel={PUBLISHED:'已發布',CANDIDATE:'待你確認',DISABLED:'已停用'}
function SkillContent({body}){
 const fields=[['適用情境','applies'],['執行步驟','steps'],['交付成果','deliverables'],['驗收標準','acceptance'],['使用工具','tools'],['能力','capabilities'],['限制與禁止事項','excludes'],['常見錯誤','common_errors'],['品質依據','quality_references'],['資料來源','sources']]
 return <div className="hy-stack"><p>{body.description}</p>{fields.map(([title,key])=>body[key]?.length?<section key={key}><h4>{title}</h4><ol>{body[key].map((text,i)=><li key={i}>{text}</li>)}</ol></section>:null)}{body.good_example&&<p><b>合格範例：</b>{body.good_example}</p>}{body.reject_example&&<p><b>不合格範例：</b>{body.reject_example}</p>}<details><summary>完整工作說明</summary><div style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{body.markdown?.replace(/^---[\s\S]*?---\n/,'').replace(/^#{1,6} /gm,'')}</div></details><details><summary>技術資訊</summary><p>識別：{body.id} · 版本：{body.version}</p><p className="hy-note">{body.content_hash}</p><p>維護者：{body.maintainer}</p><p>發布依據：{body.publication_basis}</p></details></div>
}
export default function ExpertTeam(){
 const [data,setData]=useState(null),[tab,setTab]=useState('experts'),[version,setVersion]=useState('2.1.0'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[contents,setContents]=useState({}),[projects,setProjects]=useState([]),[project,setProject]=useState(''),[requests,setRequests]=useState([]),[search,setSearch]=useState('')
 async function load(){setData(await api('/experts/registry'))}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 useEffect(()=>{if(tab==='requests')api('/projects').then(setProjects).catch(e=>setError(e.message))},[tab])
 async function act(fn){setBusy(true);setError('');try{await fn();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function key(s){return `${s.id}:${s.version}:${s.content_hash}`}
 async function read(s){const body=await api(`/experts/pi/skills/${s.id}/${s.version}/${s.content_hash}`);setContents(prev=>({...prev,[key(s)]:body}))}
 const skills=(data?.skills||[]).filter(s=>s.id==='pi-integrator'&&s.version===version)
 const pins=skills.map(({id,version,content_hash})=>({id,version,content_hash}))
 const canExpert=skills.length===1&&skills[0].state==='PUBLISHED'
 const expertActions=(data?.actions||[]).filter(a=>a.payload.expert)
 function decisions(a,readable){return <div className="pi-controls"><button className="hy-btn is-primary" disabled={busy||!readable} onClick={()=>act(()=>api(`/inbox/${a.id}/resolve`,{answer:'APPROVED'}))}>核准此版本發布</button><button className="hy-btn" disabled={busy} onClick={()=>act(()=>api(`/inbox/${a.id}/resolve`,{answer:'REJECTED'}))}>拒絕發布</button></div>}
 const skillGroups=grouped(data?.skills).filter(rows=>`${rows[0].name} ${rows[0].description}`.toLowerCase().includes(search.toLowerCase()))
 const expertGroups=grouped(data?.experts).filter(rows=>`${rows[0].name} ${rows[0].id} ${rows[0].capabilities?.join(' ')}`.toLowerCase().includes(search.toLowerCase()))
 async function remove(s){if(!window.confirm(`刪除「${s.name}」版本 ${s.version}？此操作會移除內容與尚未完成的發布申請，無法還原。`))return;await act(()=>api('/experts/skills/delete-version',{id:s.id,version:s.version,content_hash:s.content_hash}))}
 return <div className="hy expert-team hy-stack"><div className="hy-pagehead"><div><h1 className="hy-title">專家團</h1><p className="hy-lede">集結專業能力，協助你完成更大的目標。</p></div><button className="hy-btn" disabled={busy} onClick={()=>act(load)}>重新整理</button></div>
 {error&&<p role="alert" className="hy-alert">{error}</p>}{!data&&!error&&<p className="hy-empty">讀取中…</p>}
 <nav className="hy-tabs">{[['experts','專家列表'],['skills','Skill 管理'],['requests','能力請求']].map(([id,label])=><button className="hy-tab" key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setSearch('')}}>{label}</button>)}</nav>
 {tab!=='requests'&&<label className="pi-search">搜尋{tab==='experts'?'專家':'Skill'}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="輸入名稱或能力"/></label>}
 {tab==='experts'&&<><div className="expert-grid">{expertGroups.map(rows=>{const e=rows.find(e=>e.state==='PUBLISHED')||rows[0];return <article className="hy-card expert-card" key={e.id}><div className="hy-card-head">{e.id==='pi'?<Avatar/>:<span className="expert-symbol" aria-label="專家抽象形象">{e.name?.slice(0,2)}</span>}<Status state={e.state}/></div><h2 className="hy-card-title">{e.id==='pi'?'PI｜專案整合專家':e.name}</h2><p className="hy-lede">{e.id==='pi'?'從想法到實現，整合全局，提出有依據的方向。':e.description||'專業能力依登錄內容提供。'}</p><div className="expert-tags">{e.capabilities?.map(c=><span className="hy-pill" key={c}>{c}</span>)}</div><p className="expert-meta">{e.skills.length} 個 Skill · {e.executor==='GPT_CHAT'?'GPT Chat':e.executor} · v{e.version}</p><details><summary>專家資訊與版本（{rows.length}）</summary><div className="hy-stack">{rows.map(v=><section className="pi-version" key={v.version}><div className="hy-card-head"><h3>版本 {v.version}</h3><Status state={v.state}/></div><h4>綁定 Skills</h4><ul>{v.skills.map(s=><li key={s.id}>{data.skills.find(x=>x.id===s.id)?.name||s.id} · v{s.version}<button className="hy-btn" onClick={()=>{setTab('skills');setSearch(data.skills.find(x=>x.id===s.id)?.name||s.id)}}>查看 Skill</button></li>)}</ul>{expertActions.filter(a=>a.payload.expert.id===v.id&&a.payload.expert.version===v.version).map(a=><div key={a.id}>{decisions(a,true)}</div>)}</section>)}</div></details></article>})}</div>{data&&!expertGroups.length&&<p className="hy-empty">{search?'沒有符合的專家。':'尚無已登錄專家，請先發布 Skill，再建立 Expert 候選。'}</p>}
 <details className="hy-card"><summary>新增 PI Expert 版本</summary><p>綁定已發布的 PI 專案整合 Skill，發布仍需你獨立核准。</p><div className="pi-controls"><label>Expert 版本<input aria-label="Expert 版本" value={version} onChange={e=>setVersion(e.target.value)}/></label><button className="hy-btn" disabled={busy||!canExpert} onClick={()=>act(()=>api('/experts/pi/expert-publication-request',{version,skills:pins}))}>建立 PI Expert 發布申請</button></div></details></>}
 {tab==='skills'&&<><div className="skill-grid">{skillGroups.map(rows=>{const current=rows.find(s=>s.state==='PUBLISHED')||rows[0];return <article className="hy-card" key={current.id}><div className="hy-card-head"><h2 className="hy-card-title">{current.name}</h2><Status state={current.state}/></div><p className="hy-lede skill-description">{current.description}</p><p className="expert-meta">{current.state==='PUBLISHED'?'最新發布':'最新候選'} v{current.version} · {rows.length} 個版本</p><details className="skill-versions"><summary>版本管理（{rows.length}）</summary><div className="hy-stack">{rows.map(s=>{const a=data.actions.find(a=>a.payload.skill&&key(a.payload.skill)===key(s));return <section className="pi-version" key={key(s)}><div className="hy-card-head"><h3>v{s.version}</h3><Status state={s.state}/></div><details onToggle={e=>{if(e.currentTarget.open&&!contents[key(s)])act(()=>read(s))}}><summary>查看 Skill 內容</summary>{contents[key(s)]?<SkillContent body={contents[key(s)]}/>:<p>讀取中…</p>}</details>{a&&decisions(a,!!contents[key(s)])}<div className="pi-controls"><button className="hy-btn is-danger" disabled={busy||!s.can_delete} onClick={()=>remove(s)}>刪除版本 {s.version}</button></div>{!s.can_delete&&<p className="hy-note">{s.references?.length?'此版本被專家、工作包或測試紀錄引用，無法刪除。':'此版本由系統管理，無法刪除。'}</p>}</section>})}</div></details></article>})}</div>{data&&!skillGroups.length&&<p className="hy-empty">{search?'沒有符合的 Skill。':'尚無 Skill，請先建立候選版本。'}</p>}
 <details className="hy-card"><summary>新增 PI Skill 候選版本</summary><p>一個整合 Skill 包含八項能力，發布仍需你審閱後核准。</p><div className="pi-controls"><label>Skill 版本<input aria-label="候選版本" value={version} onChange={e=>setVersion(e.target.value)}/></label><button className="hy-btn" disabled={busy} onClick={()=>act(()=>api('/experts/pi/skill-publication-requests',{version}))}>建立 PI Skill 候選與發布申請</button></div></details></>}
 {tab==='requests'&&<section className="hy-card"><h2>專案能力缺口</h2><select value={project} onChange={e=>setProject(e.target.value)}><option value="">請選專案</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><button className="hy-btn" disabled={!project||busy} onClick={()=>act(async()=>setRequests((await api(`/experts/capabilities/requests/${project}`)).requests))}>讀取所選專案缺口</button>{requests.map(r=><p key={r.request_id}>{r.need} · {r.state}</p>)}</section>}
 </div>
}
