import { useEffect, useMemo, useState } from 'react'
import { Search, RefreshCw } from 'lucide-react'
import { fetchResearchCenter, actOnResearch } from '../lifeOSApi'

const NAMES={hy:'HY','950157':'950157',family:'小因',sam:'Sam'}
const STATUS={researching:'研究中',priority:'優先研究',needs_direction:'等待方向',review_ready:'HY Review',stopped:'已停止',archived:'已封存',pro:'研究中',new:'研究中'}

export default function ResearchCenter(){
 const [data,setData]=useState({items:[],counts:{}}),[owner,setOwner]=useState(''),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('')
 async function load(){setError('');try{setData(await fetchResearchCenter({owner,status}))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[owner,status])
 const items=useMemo(()=>data.items.filter(x=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[data,query])
 async function act(item,action,ask=false){let note='';if(ask){note=window.prompt('給 Bot 的研究方向')||'';if(!note)return}setBusy(item.id);try{await actOnResearch(item.id,action,note);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 return <div className="mx-auto max-w-7xl space-y-5">
  <header className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">Bot 研究中心</h1><p className="mt-1 text-slate-500">Bots 自己研究；你有空再看，不會直接成為待辦。</p></div><button onClick={load} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><RefreshCw size={16}/>更新</button></header>
  {error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  <div className="grid grid-cols-3 gap-3"><div className="rounded-xl border bg-white p-4"><b className="text-2xl">{data.counts.total||0}</b><p className="text-sm text-slate-500">研究主題</p></div><div className="rounded-xl border bg-white p-4"><b className="text-2xl">{data.counts.needsDirection||0}</b><p className="text-sm text-slate-500">等待你的方向</p></div><div className="rounded-xl border bg-white p-4"><b className="text-2xl">{data.counts.reviewReady||0}</b><p className="text-sm text-slate-500">通過 HY Review</p></div></div>
  <div className="flex flex-wrap gap-2 rounded-xl border bg-white p-3"><select value={owner} onChange={e=>setOwner(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">全部 Bot</option>{Object.entries(NAMES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">全部狀態</option><option value="researching">研究中</option><option value="priority">優先研究</option><option value="review_ready">HY Review</option></select><label className="flex min-w-56 flex-1 items-center gap-2 rounded-lg border px-3"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋研究主題" className="w-full py-2 text-sm outline-none"/></label></div>
  <div className="grid gap-4 lg:grid-cols-2">{items.slice(0,60).map(item=>{const state=item.researchStatus||item.status||'researching';return <article key={item.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><div className="text-xs font-medium text-blue-600">{NAMES[item.owner]||item.owner}・{STATUS[state]||state}</div><h2 className="mt-1 font-semibold text-slate-900">{item.title||'未命名研究'}</h2></div><span className="text-xs text-slate-400">{item.updatedAt?.slice(0,10)||item.createdAt?.slice(0,10)||''}</span></div><p className="mt-1 text-xs text-slate-400">研究方式：RSS 情報掃描＋規則整理（此階段不使用 LLM）</p><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{item.relevance||item.summary||'Bot 正在整理關聯與證據。'}</p>{item.hyDirection&&<p className="mt-2 rounded-lg bg-blue-50 p-2 text-sm text-blue-800"><b>你的方向：</b>{item.hyDirection}</p>}{item.hyReview&&<p className="mt-2 rounded-lg bg-slate-50 p-2 text-sm"><b>HY Review：</b>{item.hyReview.summary}</p>}<div className="mt-3 flex flex-wrap gap-2"><button disabled={busy===item.id} onClick={()=>act(item,'direction',true)} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">給研究方向</button><button onClick={()=>act(item,'prioritize')} className="rounded-lg border px-3 py-2 text-sm">優先</button><button onClick={()=>act(item,'request_review')} className="rounded-lg border px-3 py-2 text-sm">送 HY Review</button><button onClick={()=>act(item,'archive')} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">封存</button></div></article>})}{!items.length&&<p className="text-slate-400">沒有符合條件的研究主題。</p>}</div>
 </div>
}
